"""20241029141443_add_new_field_to_test_items

Revision ID: 11f91b67ac61
Revises: 8f6731f8e4a6
Create Date: 2024-10-29 14:14:44.196263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f91b67ac61'
down_revision: Union[str, None] = '8f6731f8e4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_items', 'updated_at')
    # ### end Alembic commands ###
